version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - 9001:3306
    expose:
      - 9001

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9002:80
    environment:
      - PMA_ARBITRARY=1

  adminer:
    image: adminer
    restart: always
    ports:
      - 9003:8080